services:
    react:
        build:
            context: .
            dockerfile: Dockerfile.react
        volumes:
            - .:/usr/src/app
        depends_on:
            - php
        networks:
            - app-network
        command: sh -c "npm install && npm run build && npx serve build"

    php:
        build:
            context: .
            dockerfile: Dockerfile.php
        volumes:
            - .:/var/www/html
        ports:
            - "8080:80"
        networks:
            - app-network
        entrypoint: [ "docker-php-entrypoint", "apache2-foreground" ]

    db:
        image: mysql:8.4.3
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - ./docker-compose/mysql:/docker-entrypoint-initdb.d
        networks:
            - app-network

networks:
    app-network:
        name: app-network
        driver: bridge